### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by azizollahpayandeh**
Update bugs finished

### CODE REVIEW

**Comment by azizollahpayandeh** [comment]
noooooooooooooo

**Comment by spdfalcon** [comment]
چی نه؟

**Comment by azizollahpayandeh** [comment]
nothinggggggggggggggggggggggggggggggggggggggggggggggg

**Comment by spdfalcon** [comment]
🤐

**Comment by azizollahpayandeh** [comment]
kjhgidfgjfhdjghfdkjgfg

**Pull request merged**
